security:
    providers:
        user_db:
            entity: { class: Stas\CalendarBundle\Entity\User, property: username }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout: ~

        default:
            anonymous: ~

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN] }

    encoders:
        Stas\CalendarBundle\Entity\User: plaintext
